- name: Installing alacritty
  become: true
  package:
    name:
      - alacritty
- name: Run 'stow --adopt tmux' in .dotfiles
  become: false
  ansible.builtin.shell: stow --D alacritty && stow alacritty
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
