- name: Install stow
  become: true
  package:
    name:
      - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/Jason-Jay-Mason/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    version: main
