- name: Installing fish and packages for terminal
  ansible.builtin.shell: yay --noconfirm -S fisher logo-ls fish fzf fd bat
  become: false
  args:
    chdir: "{{ lookup('env', 'HOME') }}/."
- name: install devicon-lookup for icons in fzf
  ansible.builtin.shell: cargo install devicon-lookup
  become: false
  args:
    chdir: "{{ lookup('env', 'HOME') }}/."
- name: Install theme and z
  ansible.builtin.shell: fisher install jorgebucaran/hydro jethrokuan/z
  become: false
  args:
    chdir: "{{ lookup('env', 'HOME') }}/."
    executable: /usr/bin/fish
- name: Run 'stow --adopt' in .dotfiles
  ansible.builtin.shell: stow -D fish && stow fish
  become: false
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
