- name: Install
  package:
    name:
      - fish
      - fisher
      - logo-ls
- name: Install theme and z
  ansible.builtin.shell: fisher install jorgebucaran/hydro jethrokuan/z
  args:
    chdir: "{{ lookup('env', 'HOME') }}"
- name: Run 'stow --adopt tmux' in .dotfiles
  ansible.builtin.shell: stow --adopt fish
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
- name: Run 'git reset --hard' in .dotfiles
  ansible.builtin.shell: git reset --hard
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
