- name: ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
    state: directory
- name: Nerd font exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.local/share/fonts/Sauce Code Pro Nerd Font Complete.ttf"
  register: register_nerd
- name: Download and unarchive Source Code
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/SourceCodePro.zip
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
    remote_src: yes
  when: not register_nerd.stat.exists
- name: Download and unarchive Hack
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Hack.zip
    dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
    remote_src: yes
  when: not register_nerd.stat.exists
- name: Clear font cache
  ansible.builtin.shell: fc-cache -f -v
  args:
    chdir: "{{ lookup('env', 'HOME') }}"
