- name: Installing neovim and packages
  become: false
  ansible.builtin.shell: yay -S --noconfirm nvim-packer-git neovim ripgrep 
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
- name: Run 'stow --adopt' in .dotfiles
  become: false
  ansible.builtin.shell: stow -D neovim && stow neovim
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
