- name: Install
  package:
    name:
      - neovim
      - nvim-packer-git
      - ripgrep
- name: Run 'stow --adopt' in .dotfiles
  ansible.builtin.shell: stow --adopt neovim
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
- name: Run 'git reset --hard' in .dotfiles
  ansible.builtin.shell: git reset --hard
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
