- name: Install nvm
  ansible.builtin.shell: fisher install jorgebucaran/nvm.fish
  become: false
  args:
    chdir: "{{ lookup('env', 'HOME') }}/."
    executable: /usr/bin/fish
- name: Install nvm
  ansible.builtin.shell: nvm install lts && npm i -g pnpm
  become: false
  args:
    chdir: "{{ lookup('env', 'HOME') }}/."
    executable: /usr/bin/fish
- name: Set lts as default accross sessions
  ansible.builtin.shell: set --universal nvm_default_version lts
  become: false
  args:
    chdir: "{{ lookup('env', 'HOME') }}/."
    executable: /usr/bin/fish
