- name: Install
  become: true
  package:
    name:
      - tmux
- name: Run 'stow --adopt tmux' in .dotfiles
  ansible.builtin.shell: stow -D tmux && stow tmux
  become: false
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
